/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface LoanStorageInterface extends Interface {
    getFunction(nameOrSignature: "activeLoans" | "loanRequests" | "totalLoans" | "totalRequests"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'activeLoans', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'loanRequests', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalLoans', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRequests', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'activeLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'loanRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRequests', data: BytesLike): Result;
  }

  

  export interface LoanStorage extends BaseContract {
    
    connect(runner?: ContractRunner | null): LoanStorage;
    waitForDeployment(): Promise<this>;

    interface: LoanStorageInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activeLoans: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {borrower: string, lender: string, loanAmount: bigint, startTimestamp: bigint, stake: bigint, endTime: bigint, interestRate: bigint, isRepaid: boolean, initialEthPrice: bigint }],
      'view'
    >
    

    
    loanRequests: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean, bigint, bigint] & {borrower: string, loanAmount: bigint, duration: bigint, isActive: boolean, stake: bigint, interestRate: bigint }],
      'view'
    >
    

    
    totalLoans: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRequests: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activeLoans'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {borrower: string, lender: string, loanAmount: bigint, startTimestamp: bigint, stake: bigint, endTime: bigint, interestRate: bigint, isRepaid: boolean, initialEthPrice: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'loanRequests'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean, bigint, bigint] & {borrower: string, loanAmount: bigint, duration: bigint, isActive: boolean, stake: bigint, interestRate: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'totalLoans'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRequests'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }