/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace LoanTypes {
      
    export type ActiveLoanStruct = {borrower: AddressLike, lender: AddressLike, loanAmount: BigNumberish, startTimestamp: BigNumberish, stake: BigNumberish, endTime: BigNumberish, interestRate: BigNumberish, isRepaid: boolean, initialEthPrice: BigNumberish}

    export type ActiveLoanStructOutput = [borrower: string, lender: string, loanAmount: bigint, startTimestamp: bigint, stake: bigint, endTime: bigint, interestRate: bigint, isRepaid: boolean, initialEthPrice: bigint] & {borrower: string, lender: string, loanAmount: bigint, startTimestamp: bigint, stake: bigint, endTime: bigint, interestRate: bigint, isRepaid: boolean, initialEthPrice: bigint }
  

    export type LoanRequestStruct = {borrower: AddressLike, loanAmount: BigNumberish, duration: BigNumberish, isActive: boolean, stake: BigNumberish, interestRate: BigNumberish}

    export type LoanRequestStructOutput = [borrower: string, loanAmount: bigint, duration: bigint, isActive: boolean, stake: bigint, interestRate: bigint] & {borrower: string, loanAmount: bigint, duration: bigint, isActive: boolean, stake: bigint, interestRate: bigint }
  
    }

  export interface LendingPlatformInterface extends Interface {
    getFunction(nameOrSignature: "MAX_INTEREST_RATE" | "activeLoans" | "checkLoanStatus" | "createLoanRequest" | "fundLoanRequest" | "getAllActiveLoans" | "getBorrowerActiveLoans" | "getRepayAmount" | "liquidateExpiredLoan" | "loanRequests" | "repayLoan" | "totalLoans" | "totalRequests"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "LoanFunded" | "LoanLiquidated" | "LoanRepaid" | "LoanRequestCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_INTEREST_RATE', values?: undefined): string;
encodeFunctionData(functionFragment: 'activeLoans', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'checkLoanStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createLoanRequest', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundLoanRequest', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllActiveLoans', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBorrowerActiveLoans', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRepayAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'liquidateExpiredLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'loanRequests', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'repayLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalLoans', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRequests', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_INTEREST_RATE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkLoanStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLoanRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundLoanRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllActiveLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrowerActiveLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRepayAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liquidateExpiredLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'loanRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLoans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRequests', data: BytesLike): Result;
  }

  
    export namespace LoanFundedEvent {
      export type InputTuple = [loanId: BigNumberish, requestId: BigNumberish, lender: AddressLike, borrower: AddressLike, loanAmount: BigNumberish, stake: BigNumberish, initialEthPrice: BigNumberish];
      export type OutputTuple = [loanId: bigint, requestId: bigint, lender: string, borrower: string, loanAmount: bigint, stake: bigint, initialEthPrice: bigint];
      export interface OutputObject {loanId: bigint, requestId: bigint, lender: string, borrower: string, loanAmount: bigint, stake: bigint, initialEthPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanLiquidatedEvent {
      export type InputTuple = [loanId: BigNumberish, lender: AddressLike, stake: BigNumberish];
      export type OutputTuple = [loanId: bigint, lender: string, stake: bigint];
      export interface OutputObject {loanId: bigint, lender: string, stake: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRepaidEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, repayAmount: BigNumberish];
      export type OutputTuple = [loanId: bigint, borrower: string, lender: string, repayAmount: bigint];
      export interface OutputObject {loanId: bigint, borrower: string, lender: string, repayAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRequestCreatedEvent {
      export type InputTuple = [requestId: BigNumberish, borrower: AddressLike, loanAmount: BigNumberish, durationInDays: BigNumberish, interestRate: BigNumberish, stake: BigNumberish];
      export type OutputTuple = [requestId: bigint, borrower: string, loanAmount: bigint, durationInDays: bigint, interestRate: bigint, stake: bigint];
      export interface OutputObject {requestId: bigint, borrower: string, loanAmount: bigint, durationInDays: bigint, interestRate: bigint, stake: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LendingPlatform extends BaseContract {
    
    connect(runner?: ContractRunner | null): LendingPlatform;
    waitForDeployment(): Promise<this>;

    interface: LendingPlatformInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_INTEREST_RATE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activeLoans: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {borrower: string, lender: string, loanAmount: bigint, startTimestamp: bigint, stake: bigint, endTime: bigint, interestRate: bigint, isRepaid: boolean, initialEthPrice: bigint }],
      'view'
    >
    

    
    checkLoanStatus: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [[boolean, bigint, bigint, bigint, bigint, bigint] & {isRepaid: boolean, loanAmount: bigint, startTimestamp: bigint, endTime: bigint, interestRate: bigint, initialEthPrice: bigint }],
      'view'
    >
    

    
    createLoanRequest: TypedContractMethod<
      [_loanAmount: BigNumberish, _durationInDays: BigNumberish, _interestRate: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    fundLoanRequest: TypedContractMethod<
      [_requestId: BigNumberish, _initialEthPrice: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getAllActiveLoans: TypedContractMethod<
      [],
      [[bigint[], LoanTypes.ActiveLoanStructOutput[], bigint[], LoanTypes.LoanRequestStructOutput[]] & {loanIds: bigint[], loans: LoanTypes.ActiveLoanStructOutput[], requestIds: bigint[], requests: LoanTypes.LoanRequestStructOutput[] }],
      'view'
    >
    

    
    getBorrowerActiveLoans: TypedContractMethod<
      [_borrower: AddressLike, ],
      [[bigint[], LoanTypes.LoanRequestStructOutput[]] & {loanIds: bigint[], loans: LoanTypes.LoanRequestStructOutput[] }],
      'view'
    >
    

    
    getRepayAmount: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    liquidateExpiredLoan: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    loanRequests: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean, bigint, bigint] & {borrower: string, loanAmount: bigint, duration: bigint, isActive: boolean, stake: bigint, interestRate: bigint }],
      'view'
    >
    

    
    repayLoan: TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    totalLoans: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRequests: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_INTEREST_RATE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activeLoans'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {borrower: string, lender: string, loanAmount: bigint, startTimestamp: bigint, stake: bigint, endTime: bigint, interestRate: bigint, isRepaid: boolean, initialEthPrice: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'checkLoanStatus'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [[boolean, bigint, bigint, bigint, bigint, bigint] & {isRepaid: boolean, loanAmount: bigint, startTimestamp: bigint, endTime: bigint, interestRate: bigint, initialEthPrice: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'createLoanRequest'): TypedContractMethod<
      [_loanAmount: BigNumberish, _durationInDays: BigNumberish, _interestRate: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'fundLoanRequest'): TypedContractMethod<
      [_requestId: BigNumberish, _initialEthPrice: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getAllActiveLoans'): TypedContractMethod<
      [],
      [[bigint[], LoanTypes.ActiveLoanStructOutput[], bigint[], LoanTypes.LoanRequestStructOutput[]] & {loanIds: bigint[], loans: LoanTypes.ActiveLoanStructOutput[], requestIds: bigint[], requests: LoanTypes.LoanRequestStructOutput[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getBorrowerActiveLoans'): TypedContractMethod<
      [_borrower: AddressLike, ],
      [[bigint[], LoanTypes.LoanRequestStructOutput[]] & {loanIds: bigint[], loans: LoanTypes.LoanRequestStructOutput[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getRepayAmount'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'liquidateExpiredLoan'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'loanRequests'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, boolean, bigint, bigint] & {borrower: string, loanAmount: bigint, duration: bigint, isActive: boolean, stake: bigint, interestRate: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'repayLoan'): TypedContractMethod<
      [_loanId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'totalLoans'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRequests'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'LoanFunded'): TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
getEvent(key: 'LoanLiquidated'): TypedContractEvent<LoanLiquidatedEvent.InputTuple, LoanLiquidatedEvent.OutputTuple, LoanLiquidatedEvent.OutputObject>;
getEvent(key: 'LoanRepaid'): TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
getEvent(key: 'LoanRequestCreated'): TypedContractEvent<LoanRequestCreatedEvent.InputTuple, LoanRequestCreatedEvent.OutputTuple, LoanRequestCreatedEvent.OutputObject>;

    filters: {
      
      'LoanFunded(uint256,uint256,address,address,uint256,uint256,uint256)': TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
      LoanFunded: TypedContractEvent<LoanFundedEvent.InputTuple, LoanFundedEvent.OutputTuple, LoanFundedEvent.OutputObject>;
    

      'LoanLiquidated(uint256,address,uint256)': TypedContractEvent<LoanLiquidatedEvent.InputTuple, LoanLiquidatedEvent.OutputTuple, LoanLiquidatedEvent.OutputObject>;
      LoanLiquidated: TypedContractEvent<LoanLiquidatedEvent.InputTuple, LoanLiquidatedEvent.OutputTuple, LoanLiquidatedEvent.OutputObject>;
    

      'LoanRepaid(uint256,address,address,uint256)': TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
      LoanRepaid: TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
    

      'LoanRequestCreated(uint256,address,uint256,uint256,uint256,uint256)': TypedContractEvent<LoanRequestCreatedEvent.InputTuple, LoanRequestCreatedEvent.OutputTuple, LoanRequestCreatedEvent.OutputObject>;
      LoanRequestCreated: TypedContractEvent<LoanRequestCreatedEvent.InputTuple, LoanRequestCreatedEvent.OutputTuple, LoanRequestCreatedEvent.OutputObject>;
    
    };
  }